test:
  imports:
    - uv_workon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/usnistgov/uv-workon
  summary: Tools activate and run from virtual environments
  description: |
    Tools activate and run from virtual environments
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
